name: HiddenBaribiza
favicon: null
layout_spectrum: 0.34834
typography_spectrum: 0.51418
title: Hidden Bar ibiza
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ede2e6'
    - '#dc69b0'
    - '#111008'
    - '#69797e'
    - '#b12172'
  brandStrength: 0.5
  lightness: 0.770523734157905
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
